"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.coms = exports.PRESENCE_PENALTY = exports.TOP_P = exports.FREQUENCY_PENALTY = exports.TEMERATURE = exports.MAX_TOKENS = void 0;
var openAI_1 = require("./openAI");
Object.defineProperty(exports, "MAX_TOKENS", { enumerable: true, get: function () { return openAI_1.MAX_TOKENS; } });
Object.defineProperty(exports, "TEMERATURE", { enumerable: true, get: function () { return openAI_1.TEMERATURE; } });
Object.defineProperty(exports, "FREQUENCY_PENALTY", { enumerable: true, get: function () { return openAI_1.FREQUENCY_PENALTY; } });
Object.defineProperty(exports, "TOP_P", { enumerable: true, get: function () { return openAI_1.TOP_P; } });
Object.defineProperty(exports, "PRESENCE_PENALTY", { enumerable: true, get: function () { return openAI_1.PRESENCE_PENALTY; } });
Object.defineProperty(exports, "coms", { enumerable: true, get: function () { return openAI_1.coms; } });
